import asyncio
import os
import sys
import json

from typing import Optional # hits for optional values
from contextlib import AsyncExitStack # manage multiple async tasks
from mcp import ClientSession,StdioServerParameters
from mcp.client.stdio import stdio_client

from google import genai
from google.genai import types
from google.genai.types import Tool, FunctionDeclaration
from google.genai.types import GenerateContentConfig 

from dotenv import load_dotenv

load_dotenv()

class MCPClient:
    def __init__(self):
        self.session : Optional[ClientSession] = None
        self.exit_stack = AsyncExitStack()

        gemini_api_key = os.getenv("GEMINI_API_KEY")
        if not gemini_api_key:
            raise ValueError("GEMINI_API_KEY not found. Please add it to your ,env")
        
        self.genai_client = genai.Client(api_key = gemini_api_key)

    async def connect_to_server(self, server_script_path:str ):
        command = "python" if server_script_path.endswith('.py') else "node"

        server_params = StdioServerParameters(command=command, args=[server_script_path])

        #establish communication withthe MCP server using standard input/output(sstdio)
        stdio_transport = await self.exit_stack.enter_async_context(stdio_client(server_params))

        self.stdio,self.write = stdio_transport

        self.session = await self.exit_stack.enter_async_context(ClientSession(self.stdio,self.write))

        await self.session.initialize()

        response = await self.session.list_tools()

        tools= response.tools

        print("\n Connected to server with tools:", [tool.name for tool in tools])

        self.function_declarations = convert_mcp_tools_to_gemini(tools)

    async def process_query(self, query: str) -> str:
        """
        process a user query using gemini api and execute tool calls if needed.

        Args:
            query(str): The user's input query

        Returns : 
            str: The response generated by the gemini model

        """

        user_prompt_content = types.Content(
            role = 'user', # Indicates that this is user message.
            parts = [types.Part.from_text(text=query)]
        )

        response = self.genai_client.models.generate_content(
            model='gemini-2.5-flash-lite',  # Specifies which Gemini model to use
            contents=[user_prompt_content],  # Send user input to Gemini
            config=types.GenerateContentConfig(
                tools=self.function_declarations,  # Pass the list of available MCP tools for Gemini to use
            ),
        )

        final_text = []
        assistant_message_content = []

        for candidate in response.candidates:
            if candidate.content.parts:
                for part in candidate.content.parts:
                    if isinstance(part, types.Part):
                        if part.function_call:
                            function_call_part = part
                            tool_name = function_call_part.function_call.name
                            tool_args = function_call_part.function_call.args

                            print(f"\n[Gemini requested tool call:{tool_name} with args{tool_args}]")

                            #execute the tool using the MCP server

                            try:
                                result = await self.session.call_tool(tool_name, tool_args)
                                function_response = {"result": result.content}
                            except Exception as e:
                                function_response = {"error": str(e)}

                            function_response_part = types.Part.from_function_response(
                                name = tool_name,
                                response= function_response
                            )

                            function_response_content = types.Content(
                                role = 'tool',
                                parts = [function_response_part]
                            )

                            response = self.genai_client.models.generate_content(
                                model='gemini-2.5-flash-lite',  # Use the same model
                                contents=[
                                    user_prompt_content, #original user query
                                    function_call_part, #include Gemini's funtion call request
                                    function_response_content, # Include tool execution result
                                ],
                                config=types.GenerateContentConfig(
                                    tools=self.function_declarations,
                                ),
                            )
                            print( response)
                            final_text.append(response.candidates[0].content.parts[0].text)
                        else:
                            # If no function call was requested, simply add Gemini's text response
                            final_text.append(part.text)

        # Return the combined response as a single formatted string
        return "\n".join(final_text)

    async def chat_loop(self):
        """ Run interactive chat session with the user"""
        print("\nMCP Client Started! Type 'quit' to exit.")

        while True:
            query = input("\n Qyery: ").strip()
            if query.lower() == 'quit':
                break

            response = await self.process_query(query)
            print("\n" + response)

    async def cleanup(self):
        await self.exit_stack.aclose()

def clean_schema(schema):
    """
    Recursively removes 'title' fields from the JSON schema.

        Args: 
            schema(dict); schema dictionary.

        Returns:
                dict: Cleaned schema without 'title' fields.

        """

    if isinstance(schema,dict):
        schema.pop("title", None)

        #recursively clean nested properties
        if "properties" in schema and isinstance(schema['properties'],dict):
            for key in schema["properties"]:
                schema["properties"][key] = clean_schema(schema["properties"][key])
    
    return schema

def convert_mcp_tools_to_gemini(mcp_tools):
    """
    Converts MCP tool definitions to the correct format for Gemini API function calling.

        Args:
            mcp_tools (list): List of MCP tool objects with 'name', 'description', and 'inputSchema'.

        Returns:
            list: List of Gemini Tool objects with properly formatted function declarations.
        """

    gemini_tools =[]
    for tool in mcp_tools:
        parameters = clean_schema(tool.inputSchema)

        function_declaration = FunctionDeclaration(
                name = tool.name,
                description = tool.description,
                parameters = parameters
        )

        gemini_tool = Tool(function_declarations = [function_declaration])
        gemini_tools.append(gemini_tool)
    return gemini_tools



async def main():
    """Main function to start the MCP client."""
    if len(sys.argv) < 2:
        print("Usage: python client.py <path_to_server_script>")
        sys.exit(1)

        print(dir())

        if 'MCPClient' not in dir():
            print("MCPClient is not defined.")
            
    client = MCPClient()
    try:
        # Connect to the MCP server and start the chat loop
        await client.connect_to_server(sys.argv[1])
        await client.chat_loop()
    finally:
        # Ensure resources are cleaned up
        await client.cleanup()

if __name__ == "__main__":
    # Run the main function within the asyncio event loop
    asyncio.run(main())


